### ISSUE TITLE
can’t establish a connection to the server at wss://meet.jit.si/xmpp-websocket?room=my-secret-conference.

### ISSUE THREAD

**Issue by s-light** [jurcello/jitsi-vue-tutorial#4]
i just cloned and tried your example app.
but on click of the `Connect` button i get  error in the dev console:
`GET wss://meet.jit.si/xmpp-websocket?room=my-secret-conference  [HTTP/1.1 403 Forbidden 304ms]`

[developer.mozilla.org on 403 error code:](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)
> The HTTP 403 Forbidden client error status response code indicates that the server understood the request but refuses to authorize it.
> This status is similar to 401, but in this case, re-authenticating will make no difference. 
> The access is permanently forbidden and tied to the application logic, such as insufficient rights to a resource.

i found [this topic in the jitsi community forum](https://community.jitsi.org/t/websocket-connection-establish-error/93364) - but as fare as i understand it only state that the tokenised version is only available in the jitsi as a service version...

does this code still work for you with the public service?

**Comment by s-light** [comment]
ok seems that this low-level usage of meet.jit.si is not allowed.
maybe that change some time in the past.
i got [an answer in the jitsi forum:](https://community.jitsi.org/t/can-t-establish-a-connection-to-the-server-at-wss-meet-jit-si-xmpp-websocket-room-xxx/93747/2)

> [damencho](https://community.jitsi.org/u/damencho)
> On meet.jit.si you should be using the iframe API there as per the [terms and conditions](http://jitsi.org/meet-jit-si-terms-of-service/) of that service.
> You may want to try https://jaas.8x8.vc though. We can probably help you achieve the same thing there.

i will leave this open for some days and then close it.

**Comment by jurcello** [comment]
Good to know. Didn't know that. Thanks for the info!
